# Copyright (c) 2021 Nordic Semiconductor ASA
# SPDX-License-Identifier: Apache-2.0

manifest:
  self:
    path: helium_meteo

  remotes:
    - name: upstream
      url-base: https://github.com/zephyrproject-rtos
    - name: dinuxbg
      url-base: https://github.com/dinuxbg

  projects:
    - name: zephyr
      remote: dinuxbg
      revision: stm32_i2c_pm_fix
      import:
        name-allowlist:
          - hal_stm32
          - cmsis
          - tinycrypt
          - loramac-node
